version: '3.4'

networks:
  local:
    driver: "bridge"

volumes:
  mysql-data:
    driver: local

services:
  app:
    build:
      context: ./compose/php
      dockerfile: Dockerfile
    container_name: "${DOCKER_PREFIX_NAME}-app"
    ports:
      - "${DOCKER_APP_PORT:-80}:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - local
  mysql:
    image: mysql:8.0.34
    container_name: "${DOCKER_PREFIX_NAME}-mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "${DOCKER_MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./compose/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    networks:
      - local