version: "3"

services:
    app:
      build:
        context: .
        dockerfile: compose/8.2/Dockerfile
      container_name: "${DOCKER_PREFIX_NAME}-app"
      volumes:
        - './src:/var/www/html'
        - './compose/8.2/rootfs/etc/supervisord/supervisord.ini:/etc/supervisor.d/supervisord.ini'
        - './compose/8.2/rootfs/etc/crontab:/etc/crontabs/root'
        - './compose/8.2/rootfs/etc/php/local.ini:/usr/local/etc/php/php.ini'
        - './compose/8.2/rootfs/etc/nginx/nginx.conf:/etc/nginx/nginx.conf'
        - './compose/8.2/rootfs/etc/nginx/conf.d/default.conf:/etc/nginx/http.d/default.conf'
      networks:
        - local
    mysql:
      image: mysql:8.0.34
      container_name: "${DOCKER_PREFIX_NAME}-mysql"
      environment:
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        MYSQL_ROOT_HOST: "%"
        MYSQL_PASSWORD: "${DB_PASSWORD}"
        MYSQL_USER: "${DB_USERNAME}"
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      ports:
        - "${DOCKER_MYSQL_PORT:-3306}:3306"
      volumes:
        - 'mysql-data:/var/lib/mysql'
#        - './compose/mysql/conf.d/my.cnf:/etc/mysql/conf.d.d/my.cnf'
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
        retries: 3
        timeout: 5s
      networks:
        - local

volumes:
    mysql-data:

networks:
    local:
      driver: bridge